---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "my-app-service"
  labels:
    app: "my-app"
spec:
  ports:
  - protocol: "TCP"
    port: 3001
    targetPort: 3000
  selector:
    app: "my-app"
  type: "LoadBalancer"
  loadBalancerIP: "192.168.0.10"
